- upgrade_d7_language_types
- upgrade_d7_system_maintenance_translation
- upgrade_d7_system_site_translation
- upgrade_d7_user_mail_translation
- upgrade_d7_user_settings_translation
- upgrade_locale_settings
- upgrade_update_settings
- upgrade_language
- upgrade_d7_field_instance_label_description_translation
- upgrade_d7_field_instance_option_translation
- upgrade_d7_field_option_translation
- upgrade_d7_language_content_comment_settings
- upgrade_d7_language_content_settings
- upgrade_d7_language_content_taxonomy_vocabulary_settings
- upgrade_d7_language_negotiation_settings
- upgrade_default_language
- upgrade_d7_taxonomy_vocabulary_translation
- upgrade_language_prefixes_and_domains
