- upgrade_d7_global_theme_settings
- upgrade_d7_pathauto_settings
- upgrade_d7_search_page
- upgrade_d7_theme_settings
- upgrade_d7_view_modes
- upgrade_d7_pathauto_patterns
- upgrade_block_content_type
- upgrade_block_content_body_field
- upgrade_block_content_entity_display
- upgrade_block_content_entity_form_display
- upgrade_user_picture_field
